#!/usr/bin/env python


# Return tile information
def _ti4_load_planets():
    # tiles is a vector of tuples
    #   each tuple consists of planet number, name, number of resource, number of influence,
    #   bool for whether tile is a wormhole,
    #   bool for whether tile is an anomaly,
    #   bool for whether tile is a blank,
    return [
        (18, "Mecatol Rex", 1, 6, False, False, False),
        (35, "Bereg, Lirta IV", 5, 4, False, False, False),
        (38, "Abyz, Fria", 5, 0, False, False, False),
        (27, "New Albion, Starpoint", 4, 2, False, False, False),
        (36, "Arnor, Lor", 3, 3, False, False, False),
        (30, "Mellon, Zohbat", 3, 3, False, False, False),
        (33, "Corneeq, Resculon", 3, 2, False, False, False),
        (26, "Lodor", 3, 1, True, False, False),
        (31, "Lazar, Sakulag", 3, 1, False, False, False),
        (34, "Centauri, Gral", 2, 4, False, False, False),
        (28, "Tequ'ran, Torkan", 2, 3, False, False, False),
        (20, "Vefut II", 2, 2, False, False, False),
        (23, "Saudor", 2, 2, False, False, False),
        (25, "Quann", 2, 1, True, False, False),
        (37, "Arinam, Meer", 1, 6, False, False, False),
        (29, "Qucen'n, Rarron", 1, 5, False, False, False),
        (24, "Mehar Xull", 1, 3, False, False, False),
        (32, "Dal Bootha, Xxehan", 1, 3, False, False, False),
        (19, "Wellon", 1, 2, False, False, False),
        (22, "Tar'mann", 1, 1, False, False, False),
        (21, "Thibah", 1, 1, False, False, False),
        (39, "A Wormhole", 0, 0, True, False, False),
        (40, "B Wormhole", 0, 0, True, False, False),
        (44, "Asteroid Field", 0, 0, False, True, False),
        (45, "Asteroid Field", 0, 0, False, True, False),
        (43, "Supernova", 0, 0, False, True, False),
        (42, "Nebula", 0, 0, False, True, False),
        (41, "Gravity Rift", 0, 0, False, True, False),
        (46, "Blank", 0, 0, False, False, True),
        (47, "Blank", 0, 0, False, False, True),
        (48, "Blank", 0, 0, False, False, True),
        (49, "Blank", 0, 0, False, False, True),
        (50, "Blank", 0, 0, False, False, True),
    ]
